version: '3.3'
services:
  user_db:
    image: postgres:14-alpine
    ports:
      - '15111:5432'
    restart: 'no'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret99
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - backend-network

networks:
  backend-network:
    driver: bridge

volumes:
  db:
    driver: local
